services:
    db:
        image: postgres:16
        container_name: postgres-db
        environment:
            POSTGRES_USER: baerchen_dev
            POSTGRES_PASSWORD: 3ip_tsi_95141.3
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_dev_data:/var/lib/postgresql/master-dev-data

volumes:
    postgres_dev_data: